### ISSUE TITLE
json第750行少了个逗号, 导致加载失败.

### ISSUE THREAD

**Issue by pengjiaxusz** [dtlnor/stable-diffusion-webui-localization-zh_CN#12]
![image](https://user-images.githubusercontent.com/86648773/227750478-c653069b-8a34-4cfd-ae71-b8da595f1c2e.png)

**Comment by dajusha** [comment]
多谢楼主方法，我还纳闷怎么语言失效了
但是改好了这个，https://github.com/journey-ad/sd-webui-bilingual-localization 还是无效。

**Comment by surfishs** [comment]
感谢楼主！

**Comment by ohhhyy** [comment]
感谢楼主 可以用了

**Comment by dtlnor** [comment]
fixed in #13
