### ISSUE TITLE
json格式错误，在双语设置后

### ISSUE THREAD

**Issue by withyun** [dtlnor/stable-diffusion-webui-localization-zh_CN#15]
VM4911:751 Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 37924
验证到这一步后
 i18n = JSON.parse(readFile(dirs[file]), (key, value) => {
      // parse regex translations
      if (key.startsWith('@@')) {
        i18nRegex[key.slice(2)] = value
      } else {
        return value
      }
    })

**Comment by dtlnor** [comment]
嘗試更新語言包到最新版本試試

**Comment by withyun** [comment]
> 嘗試更新語言包到最新版本試試

OK 了，thanks
