### ISSUE TITLE
下载zip包放入extensions根目录 扩展已经正确加载最后点击Apply settings错误

### ISSUE THREAD

**Issue by Mr-lins** [dtlnor/stable-diffusion-webui-localization-zh_CN#18]
![c6646496a36bd75bc4cebe6396d945b](https://user-images.githubusercontent.com/26573094/229818844-e7cae9ec-f57c-49df-b076-df5e7ff731fd.png)

**Comment by ABaoShuai** [comment]
请问下怎么删除插件的，我也报错了
![image](https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN/assets/102342842/4a5ad39a-5640-4782-a370-ee1439d6ec7e)

**Comment by dtlnor** [comment]
> 请问下怎么删除插件的，我也报错了 ![image](https://user-images.githubusercontent.com/102342842/238809491-4a5ad39a-5640-4782-a370-ee1439d6ec7e.png)

@ABaoShuai  webui根目录下的extension目录里面
