### ISSUE TITLE
写了一个第三方翻译扩展，可以实现双语对照翻译

### ISSUE THREAD

**Issue by journey-ad** [dtlnor/stable-diffusion-webui-localization-zh_CN#9]
https://github.com/journey-ad/sd-webui-bilingual-localization

部分翻译文本来源于本仓库，对本仓库翻译/维护人员表示感谢   
是否可以将功能整合至本仓库，在设置中加上一个选项，允许用户选择官方或是扩展的多语言实现？

界面预览：
![Snipaste_2023-02-26_19-14-13](https://user-images.githubusercontent.com/16256221/221407103-0c231a44-32ed-4d98-8385-eeb66656ae81.png)

**Comment by MiyouQ** [comment]
这个好 有些翻成中文 看教程的时候反而找不到英文对照了

**Comment by dtlnor** [comment]
这是一个很好的插件。不过整合进我的repo可能会有不太利于代码维护的问题，每次更新我们都要互相拷贝代码。
所以可能解决方法有：
1. 使用install.py，在加载我这个插件的同时默认安装你这个插件。（我不清楚install能不能安装其他插件就是了，而且可能会有跟你的i18n.json冲突的问题）
2. 拷贝你的代码整合进这个repo，邀请你来维护这部分js代码。但这样可能就失去了让其他语言利用你的仓库的可能（当然，我们应该优先考虑自己）
3. 尝试将你的插件做得更flexible，让其自动起效于当前选择的localization（js有个global的localization可以直接利用）。我有wiki的编辑权限可以直接将你的插件添加进扩展列表

**Comment by journey-ad** [comment]
我感觉方案2和方案3都是不错的选择，其中方案3似乎更加灵活一些，用户选择空间也比较大

方案2存在的问题是，由于官方多语言实现是原文替换，所以目前流行，包括本仓库现有的一些翻译文本会带有部分原文术语方便理解功能   
而双语对照插件不需要原文，或仅在部分长说明文字中备注关键术语，事实上我也是这么做的，我的`i18n.json`整合了流行的翻译文本，并剔除了其中的原文备注   
但为了一个第三方扩展修改翻译文本似乎不太妥当，会影响到常规用户使用。一个可选方案是维护两种语料（带/不带原文术语）

所以我倾向于方案3，完善这个双语插件，使其支持选择翻译json。后续我看下其他语种的兼容情况，然后对代码规范和性能改善优化后尝试发布到扩展列表

**Comment by journey-ad** [comment]
我已经改写了这个插件，现在可以在设置面板从 localization 列表中选择不同的语言包了

可以安装体验下，可行的话烦请添加进扩展列表里

![](https://user-images.githubusercontent.com/16256221/221625729-73519629-8c1f-4eb5-99db-a1d3f4b58a87.png)

**Comment by dtlnor** [comment]
> 我已经改写了这个插件，现在可以在设置面板从 localization 列表中选择不同的语言包了
> 
> 可以安装体验下，可行的话烦请添加进扩展列表里
> 
> ![](https://user-images.githubusercontent.com/16256221/221625729-73519629-8c1f-4eb5-99db-a1d3f4b58a87.png)

！能用了
我已经在扩展列表里面修改好了，如果有什么description或者简介要更改的还请告知我。

**Comment by journey-ad** [comment]
> ！能用了 我已经在扩展列表里面修改好了，如果有什么description或者简介要更改的还请告知我。

非常感谢！有个疑问是分类放到`localization`里边会不会更合适一点，因为是必须要搭配其他语言包使用的

**Comment by dtlnor** [comment]
> > ！能用了 我已经在扩展列表里面修改好了，如果有什么description或者简介要更改的还请告知我。
> 
> 
> 
> 非常感谢！有个疑问是分类放到`localization`里边会不会更合适一点，因为是必须要搭配其他语言包使用的
> 
> 

我是考虑到通常人们会默认钩上排除localization所以放在了script分类。因为怕旧用户看不见。即使是新用户安装localization之后也有机会看到这个插件。虽然localization会是比较恰当的分类，你觉得呢？

**Comment by journey-ad** [comment]
> > > ！能用了 我已经在扩展列表里面修改好了，如果有什么description或者简介要更改的还请告知我。
> > 
> > 
> > 非常感谢！有个疑问是分类放到`localization`里边会不会更合适一点，因为是必须要搭配其他语言包使用的
> 
> 我是考虑到通常人们会默认钩上排除localization所以放在了script分类。因为怕旧用户看不见。即使是新用户安装localization之后也有机会看到这个插件。虽然localization会是比较恰当的分类，你觉得呢？

也许两个都选上？或者`localization`和`UI related`这两个分类会不会更好一点

**Comment by dtlnor** [comment]
> 也许两个都选上？或者`localization`和`UI related`这两个分类会不会更好一点

可以是可以，但这样无论勾选（也就是排除）`localization`还是`UI related`都会让他看不见。而默认勾选的`localization`会让不勾选`UI related`的用户依旧看不到这个插件。这样可以吗？

**Comment by journey-ad** [comment]
> > 也许两个都选上？或者`localization`和`UI related`这两个分类会不会更好一点
> 
> 可以是可以，但这样无论勾选（也就是排除）`localization`还是`UI related`都会让他看不见。而默认勾选的`localization`会让不勾选`UI related`的用户依旧看不到这个插件。这样可以吗？

我感觉还是按照功能来分类会比较好，插件列表就那么多，总有机会看到的

**Comment by dtlnor** [comment]
> > > 也许两个都选上？或者`localization`和`UI related`这两个分类会不会更好一点
> > 
> > 
> > 可以是可以，但这样无论勾选（也就是排除）`localization`还是`UI related`都会让他看不见。而默认勾选的`localization`会让不勾选`UI related`的用户依旧看不到这个插件。这样可以吗？
> 
> 我感觉还是按照功能来分类会比较好，插件列表就那么多，总有机会看到的

改好了，你可以看看有没有问题，其他一些简介之类的如果有需求改也可以跟我说

**Comment by journey-ad** [comment]
> 改好了，你可以看看有没有问题，其他一些简介之类的如果有需求改也可以跟我说

感谢支持！应该没有其他需要操作的，你觉得合适的话可以关掉这个 issue 了
